In [362]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [363]:
df=pd.read_csv('data/eksikveriler.csv')

In [364]:
boy=df[['boy']]

In [365]:
print(boy)

    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166


In [366]:
boykilo=df[['boy', 'kilo']]

In [367]:
class insan:
    boy=180
    def kosmak(self, b):
        return b+10

In [368]:
ali=insan()

In [369]:
print(ali.boy)

180


In [370]:
print(ali.kosmak(90))

100


In [371]:
l=[1,2,3,4]

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

Yas=df.iloc[:,1:4].values
print(Yas)
imputer=imputer.fit(Yas[:,1:4])
Yas[:,1:4]=imputer.transform
print(Yas)

In [372]:
df.yas=df.yas.fillna(df.yas.mean())

In [373]:
ulke=df.iloc[:,0:1].values

In [374]:
ulke

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [375]:
le=preprocessing.LabelEncoder()

In [376]:
ulke[:,0]=le.fit_transform(df.iloc[:,0])

In [377]:
ulke

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [378]:
ohe=preprocessing.OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()

In [379]:
print(ulke)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [380]:
sonuc=pd.DataFrame(data=ulke, index=range(22), columns=['fr', 'tr', 'us'])

In [381]:
print(sonuc)

     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0


In [382]:
sonuc2=pd.DataFrame(data=Yas, index=range(22), columns=['boy', 'kilo', 'yas'])

In [383]:
print(sonuc2)

      boy   kilo   yas
0   130.0   30.0  10.0
1   125.0   36.0  11.0
2   135.0   34.0  10.0
3   133.0   30.0   9.0
4   129.0   38.0  12.0
5   180.0   90.0  30.0
6   190.0   80.0  25.0
7   175.0   90.0  35.0
8   177.0   60.0  22.0
9   185.0  105.0  33.0
10  165.0   55.0  27.0
11  155.0   50.0  44.0
12  160.0   58.0   NaN
13  162.0   59.0  41.0
14  167.0   62.0  55.0
15  174.0   70.0  47.0
16  193.0   90.0   NaN
17  187.0   80.0  27.0
18  183.0   88.0  28.0
19  159.0   40.0  29.0
20  164.0   66.0  32.0
21  166.0   56.0  42.0


In [384]:
cinsiyet=df.iloc[:,-1].values

In [385]:
print(cinsiyet)

['e' 'e' 'k' 'k' 'e' 'e' 'e' 'e' 'k' 'e' 'k' 'k' 'k' 'k' 'k' 'e' 'e' 'e'
 'e' 'k' 'k' 'k']


In [386]:
sonuc3=pd.DataFrame(data=cinsiyet, index=range(22), columns=['cinsiyet'])
print(sonuc3)

   cinsiyet
0         e
1         e
2         k
3         k
4         e
5         e
6         e
7         e
8         k
9         e
10        k
11        k
12        k
13        k
14        k
15        e
16        e
17        e
18        e
19        k
20        k
21        k


In [387]:
s=pd.concat([sonuc, sonuc2], axis=1)
print(s)

     fr   tr   us    boy   kilo   yas
0   0.0  1.0  0.0  130.0   30.0  10.0
1   0.0  1.0  0.0  125.0   36.0  11.0
2   0.0  1.0  0.0  135.0   34.0  10.0
3   0.0  1.0  0.0  133.0   30.0   9.0
4   0.0  1.0  0.0  129.0   38.0  12.0
5   0.0  1.0  0.0  180.0   90.0  30.0
6   0.0  1.0  0.0  190.0   80.0  25.0
7   0.0  1.0  0.0  175.0   90.0  35.0
8   0.0  1.0  0.0  177.0   60.0  22.0
9   0.0  0.0  1.0  185.0  105.0  33.0
10  0.0  0.0  1.0  165.0   55.0  27.0
11  0.0  0.0  1.0  155.0   50.0  44.0
12  0.0  0.0  1.0  160.0   58.0   NaN
13  0.0  0.0  1.0  162.0   59.0  41.0
14  0.0  0.0  1.0  167.0   62.0  55.0
15  1.0  0.0  0.0  174.0   70.0  47.0
16  1.0  0.0  0.0  193.0   90.0   NaN
17  1.0  0.0  0.0  187.0   80.0  27.0
18  1.0  0.0  0.0  183.0   88.0  28.0
19  1.0  0.0  0.0  159.0   40.0  29.0
20  1.0  0.0  0.0  164.0   66.0  32.0
21  1.0  0.0  0.0  166.0   56.0  42.0


In [388]:
s2=pd.concat([s, sonuc3], axis=1)
print(s2)

     fr   tr   us    boy   kilo   yas cinsiyet
0   0.0  1.0  0.0  130.0   30.0  10.0        e
1   0.0  1.0  0.0  125.0   36.0  11.0        e
2   0.0  1.0  0.0  135.0   34.0  10.0        k
3   0.0  1.0  0.0  133.0   30.0   9.0        k
4   0.0  1.0  0.0  129.0   38.0  12.0        e
5   0.0  1.0  0.0  180.0   90.0  30.0        e
6   0.0  1.0  0.0  190.0   80.0  25.0        e
7   0.0  1.0  0.0  175.0   90.0  35.0        e
8   0.0  1.0  0.0  177.0   60.0  22.0        k
9   0.0  0.0  1.0  185.0  105.0  33.0        e
10  0.0  0.0  1.0  165.0   55.0  27.0        k
11  0.0  0.0  1.0  155.0   50.0  44.0        k
12  0.0  0.0  1.0  160.0   58.0   NaN        k
13  0.0  0.0  1.0  162.0   59.0  41.0        k
14  0.0  0.0  1.0  167.0   62.0  55.0        k
15  1.0  0.0  0.0  174.0   70.0  47.0        e
16  1.0  0.0  0.0  193.0   90.0   NaN        e
17  1.0  0.0  0.0  187.0   80.0  27.0        e
18  1.0  0.0  0.0  183.0   88.0  28.0        e
19  1.0  0.0  0.0  159.0   40.0  29.0        k
20  1.0  0.0 